# Assignments For Pandas AI Bootcamp

In [1]:
import pandas as pd
import numpy as np
print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

## Loading and Exploring the Music Dataset

In [2]:
# Loading the dataset
music = pd.read_csv('youtube-top-100-songs-2025.csv')

In [3]:
# Basic Information
print(f"Shape of Dataset: {music.shape}")
print(f"Number of rows: {len(music)}")
print(f"Number of columns: {len(music.columns)}")

Shape of Dataset: (100, 13)
Number of rows: 100
Number of columns: 13

In [4]:
# First 5 rows
music.head()

,title,fulltitle,description,view_count,categories,tags,duration,duration_string,live_status,thumbnail,channel,channel_url,channel_follower_count
0,ROSÉ & Bruno Mars - APT. (Official Music Video),ROSÉ & Bruno Mars - APT. (Official Music Video),ROSÉ & Bruno Mars - APT.\nDownload/stream: ht...,2009014557,Music,YG Entertainment;YG;와이지;K-pop;BLACKPINK;블랙핑크;블...,173,2:53,False,https://i.ytimg.com/vi_webp/ekr2nIex040/maxres...,ROSÉ,https://www.youtube.com/channel/UCBo1hnzxV9rz3...,19200000
1,"Lady Gaga, Bruno Mars - Die With A Smile (Offi...","Lady Gaga, Bruno Mars - Die With A Smile (Offi...",MAYHEM OUT NOW\nhttp://ladygaga.com \n \nListe...,1324833300,Music,Lady Gaga;Bruno Mars;Interscope;Pop,252,4:12,False,https://i.ytimg.com/vi/kPa7bsKwL-c/maxresdefau...,Lady Gaga,https://www.youtube.com/channel/UC07Kxew-cMIay...,29600000
2,Reneé Rapp - Leave Me Alone (Official Music Vi...,Reneé Rapp - Leave Me Alone (Official Music Vi...,"Listen to “BITE ME”, the new album from Reneé ...",2536628,Music,Reneé Rapp;Interscope Records;Pop,160,2:40,False,https://i.ytimg.com/vi/tiPWzFLiz4A/maxresdefau...,Reneé Rapp,https://www.youtube.com/channel/UCZy4ki_L4bzw9...,408000
3,Billie Eilish - BIRDS OF A FEATHER (Official M...,Billie Eilish - BIRDS OF A FEATHER (Official M...,Listen to HIT ME HARD AND SOFT: https://billie...,558329099,Music,Billie Eilish;Darkroom/Interscope Records;Alte...,231,3:51,False,https://i.ytimg.com/vi/V9PVRfjEBTI/maxresdefau...,Billie Eilish,https://www.youtube.com/channel/UCDGmojLIoWpXo...,56800000
4,Reneé Rapp - Mad (Official Music Video),Reneé Rapp - Mad (Official Music Video),"Listen to “BITE ME”, the new album from Reneé ...",2113548,Music,Reneé Rapp;Interscope Records;Pop,180,3:00,False,https://i.ytimg.com/vi/xkWQM3flsiY/maxresdefau...,Reneé Rapp,https://www.youtube.com/channel/UCZy4ki_L4bzw9...,408000

In [5]:
# Last 5 rows
music.tail()

,title,fulltitle,description,view_count,categories,tags,duration,duration_string,live_status,thumbnail,channel,channel_url,channel_follower_count
95,Ariana Grande - twilight zone (Official Lyric ...,Ariana Grande - twilight zone (Official Lyric ...,The official “twilight zone” official lyric vi...,18245315,Music,Ariana Grande;Republic Records;Pop,202,3:22,False,https://i.ytimg.com/vi/x1XIJM6spaE/maxresdefau...,Ariana Grande,https://www.youtube.com/channel/UC0VOyT2OCBKdQ...,56400000
96,"Gracie Abrams - I Love You, I’m Sorry (Officia...","Gracie Abrams - I Love You, I’m Sorry (Officia...","Listen to the new album, The Secret of Us, out...",31456772,Music,"Gracie Abrams;Gracie Abrams, under exclusive l...",234,3:54,False,https://i.ytimg.com/vi/uxjhN_Donfw/maxresdefau...,Gracie Abrams,https://www.youtube.com/channel/UCVFRVXH1hRoWk...,1770000
97,HoodTrophy Bino ft. FCG Heem - Miami (Official...,HoodTrophy Bino ft. FCG Heem - Miami (Official...,HoodTrophy Bino and FCG Heem drop Miami. From...,66051,Music,NaN,197,3:17,False,https://i.ytimg.com/vi_webp/I-gmbHgeN1I/maxres...,HoodTrophy Bino,https://www.youtube.com/channel/UCsaZi3QZrZ5-s...,20300
98,Sean Paul x INNA - Let It Talk To Me,Sean Paul x INNA - Let It Talk To Me,Song Title: Sean Paul x INNA - Let It Talk To ...,16952860,Music,Sean Paul,155,2:35,False,https://i.ytimg.com/vi_webp/nkRyAVQdqAA/maxres...,Sean Paul,https://www.youtube.com/channel/UCkdc7gHpavxpg...,5200000
99,"Selena Gomez, benny blanco - How Does It Feel ...","Selena Gomez, benny blanco - How Does It Feel ...",Listen to the new album 'I Said I Love You Fir...,16971256,Music,Selena Gomez;benny blanco;SMG Music LLC Friend...,161,2:41,False,https://i.ytimg.com/vi/4LcNr0T2yAA/maxresdefau...,Selena Gomez,https://www.youtube.com/channel/UCjK8ORC71kwyj...,35500000

In [6]:
# Random sample of rows
music.sample(3)

,title,fulltitle,description,view_count,categories,tags,duration,duration_string,live_status,thumbnail,channel,channel_url,channel_follower_count
50,Tate McRae - Sports car (Official Video),Tate McRae - Sports car (Official Video),"Tate McRae’s new album, ‘So Close To What’ is ...",34091789,Music,Sports car;Tate McRae;tate mcrae so close to w...,188,3:08,False,https://i.ytimg.com/vi/7InTkBxPtK4/maxresdefau...,Tate McRae,https://www.youtube.com/channel/UC-yW8iz7ICKv_...,6320000
83,Sabrina Carpenter - Busy Woman (Official Lyric...,Sabrina Carpenter - Busy Woman (Official Lyric...,"Listen to Short n’ Sweet Deluxe, out now: http...",20923612,Music,Sabrina Carpenter;Island Records;Pop;busy woma...,187,3:07,False,https://i.ytimg.com/vi/3m6NBnqLc-g/maxresdefau...,Sabrina Carpenter,https://www.youtube.com/channel/UC4mYKePIas5Yg...,12300000
98,Sean Paul x INNA - Let It Talk To Me,Sean Paul x INNA - Let It Talk To Me,Song Title: Sean Paul x INNA - Let It Talk To ...,16952860,Music,Sean Paul,155,2:35,False,https://i.ytimg.com/vi_webp/nkRyAVQdqAA/maxres...,Sean Paul,https://www.youtube.com/channel/UCkdc7gHpavxpg...,5200000

In [7]:
# Dataset info
print(music.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   100 non-null    object
 1   fulltitle               100 non-null    object
 2   description             100 non-null    object
 3   view_count              100 non-null    int64
 4   categories              100 non-null    object
 5   tags                    85 non-null     object
 6   duration                100 non-null    int64
 7   duration_string         100 non-null    object
 8   live_status             100 non-null    bool
 9   thumbnail               100 non-null    object
 10  channel                 100 non-null    object
 11  channel_url             100 non-null    object
 12  channel_follower_count  100 non-null    int64
dtypes: bool(1), int64(3), object(9)
memory usage: 9.6+ KB
None

In [8]:
# Describe numerical columns
music.describe()

         view_count    duration  channel_follower_count
count  1.000000e+02  100.000000            1.000000e+02
mean   1.059103e+08  203.900000            1.612067e+07
std    2.491132e+08   44.260592            1.980038e+07
min    1.161000e+03  120.000000            1.000000e+00
25%    1.852702e+07  173.000000            6.132500e+05
50%    3.798224e+07  193.500000            6.320000e+06
75%    1.111073e+08  231.750000            2.760000e+07
max    2.009015e+09  354.000000            7.620000e+07

In [9]:
music.dtypes

title                     object
fulltitle                 object
description               object
view_count                 int64
categories                object
tags                      object
duration                   int64
duration_string           object
live_status                 bool
thumbnail                 object
channel                   object
channel_url               object
channel_follower_count     int64
dtype: object

## Data Selection and Indexing

In [10]:
# Single Column Selection
channel_series = music['channel']
print("First 5 channels:",channel_series.head().tolist())
print("Datatype: ", type(channel_series))

First 5 channels: ['ROSÉ', 'Lady Gaga', 'Reneé Rapp', 'Billie Eilish', 'Reneé Rapp']
Datatype:  <class 'pandas.core.series.Series'>

In [11]:
# Multiple Column Selection
music_info = music[['title', 'view_count', 'channel', 'channel_follower_count']]
print("Datatype: ", type(music_info))
music_info.head()

Datatype:  <class 'pandas.core.frame.DataFrame'>

,title,view_count,channel,channel_follower_count
0,ROSÉ & Bruno Mars - APT. (Official Music Video),2009014557,ROSÉ,19200000
1,"Lady Gaga, Bruno Mars - Die With A Smile (Offi...",1324833300,Lady Gaga,29600000
2,Reneé Rapp - Leave Me Alone (Official Music Vi...,2536628,Reneé Rapp,408000
3,Billie Eilish - BIRDS OF A FEATHER (Official M...,558329099,Billie Eilish,56800000
4,Reneé Rapp - Mad (Official Music Video),2113548,Reneé Rapp,408000

In [12]:
# Single row
first_music = music.iloc[0]
print(f"First Music:\n{first_music}")
print(f"\nType of row selection: {type(first_music)}")

First Music:
title                      ROSÉ & Bruno Mars - APT. (Official Music Video)
fulltitle                  ROSÉ & Bruno Mars - APT. (Official Music Video)
description               ROSÉ & Bruno Mars - APT.\nDownload/stream: ht...
view_count                                                       2009014557
categories                                                            Music
tags                      YG Entertainment;YG;와이지;K-pop;BLACKPINK;블랙핑크;블...
duration                                                                173
duration_string                                                        2:53
live_status                                                           False
thumbnail                 https://i.ytimg.com/vi_webp/ekr2nIex040/maxres...
channel                                                                ROSÉ
channel_url               https://www.youtube.com/channel/UCBo1hnzxV9rz3...
channel_follower_count                                             19200000
Name: 0, dtype: object

Type of row selection: <class 'pandas.core.series.Series'>

In [13]:
# Multiple rows
first_five = music.iloc[0:5]
print(f"\nFirst 5 music tracks (shape: {first_five.shape}):")
first_five[['title', 'channel', 'channel_follower_count']]

First 5 music tracks (shape: (5, 13)):

,title,channel,channel_follower_count
0,ROSÉ & Bruno Mars - APT. (Official Music Video),ROSÉ,19200000
1,"Lady Gaga, Bruno Mars - Die With A Smile (Offi...",Lady Gaga,29600000
2,Reneé Rapp - Leave Me Alone (Official Music Vi...,Reneé Rapp,408000
3,Billie Eilish - BIRDS OF A FEATHER (Official M...,Billie Eilish,56800000
4,Reneé Rapp - Mad (Official Music Video),Reneé Rapp,408000

In [14]:
# Specific rows
specific_rows = music.iloc[[0, 2, 4]]
print(f"\nSpecific rows (0, 2, 4):")
specific_rows[['title', 'channel', 'channel_follower_count']]

Specific rows (0, 2, 4):

,title,channel,channel_follower_count
0,ROSÉ & Bruno Mars - APT. (Official Music Video),ROSÉ,19200000
2,Reneé Rapp - Leave Me Alone (Official Music Vi...,Reneé Rapp,408000
4,Reneé Rapp - Mad (Official Music Video),Reneé Rapp,408000

In [15]:
# Row and Column Selection
subset = music.iloc[0:5, 4:8]  # First 5 rows, columns 4-7
subset

,categories,tags,duration,duration_string
0,Music,YG Entertainment;YG;와이지;K-pop;BLACKPINK;블랙핑크;블...,173,2:53
1,Music,Lady Gaga;Bruno Mars;Interscope;Pop,252,4:12
2,Music,Reneé Rapp;Interscope Records;Pop,160,2:40
3,Music,Billie Eilish;Darkroom/Interscope Records;Alte...,231,3:51
4,Music,Reneé Rapp;Interscope Records;Pop,180,3:00

In [16]:
# Using column names with loc
title_viewcount_subset= music.loc[0:4, ['title', 'view_count']]
print(f"\nUsing loc with column names:")
title_viewcount_subset

Using loc with column names:

                                               title  view_count
0   ROSÉ & Bruno Mars - APT. (Official Music Video)  2009014557
1  Lady Gaga, Bruno Mars - Die With A Smile (Offi...  1324833300
2  Reneé Rapp - Leave Me Alone (Official Music Vi...     2536628
3  Billie Eilish - BIRDS OF A FEATHER (Official M...   558329099
4            Reneé Rapp - Mad (Official Music Video)     2113548

## Data Cleaning and Handling Missing Values

In [17]:
# Check for missing values
missing_values = music.isnull().sum()
print("\nMissing values in each column:")
missing_values

Missing values in each column:

title                      0
fulltitle                  0
description                0
view_count                 0
categories                 0
tags                      15
duration                   0
duration_string            0
live_status                0
thumbnail                  0
channel                    0
channel_url                0
channel_follower_count     0
dtype: int64

In [18]:
# Handling Missing Values

music_copy = music.copy() 

# Drop rows with missing values
print(f"Original shape: {music_copy.shape}")
complete_music = music_copy.dropna()
print(f"After dropping rows with NaN: {complete_music.shape}")

Original shape: (100, 13)
After dropping rows with NaN: (85, 13)

In [19]:
# Drop specific columns with missing values
music_drop_cols = music_copy.dropna(axis=1)
print(f"After dropping columns with NaN: {music_drop_cols.shape}")

After dropping columns with NaN: (100, 12)

In [20]:
if 'tags' in music_copy.columns:
    music_copy.fillna({'tags': 'Not Found'}, inplace = True)
    print("Filled missing tags with 'Not Found'")

# Verify the filling worked
print(f"\nMissing values after filling: {music_copy.isnull().sum()}")

Filled missing tags with 'Not Found'

Missing values after filling: title                     0
fulltitle                 0
description               0
view_count                0
categories                0
tags                      0
duration                  0
duration_string           0
live_status               0
thumbnail                 0
channel                   0
channel_url               0
channel_follower_count    0
dtype: int64

# Data Filtering and Querying

In [21]:
# Single Condition
billion_viewed_music = music_copy[music_copy['view_count'] >= 1000000000]
print("Count of music viewed billion times in 2025: ", len(billion_viewed_music))
billion_viewed_music

Count of music viewed billion times in 2025:  2

,title,fulltitle,description,view_count,categories,tags,duration,duration_string,live_status,thumbnail,channel,channel_url,channel_follower_count
0,ROSÉ & Bruno Mars - APT. (Official Music Video),ROSÉ & Bruno Mars - APT. (Official Music Video),ROSÉ & Bruno Mars - APT.\nDownload/stream: ht...,2009014557,Music,YG Entertainment;YG;와이지;K-pop;BLACKPINK;블랙핑크;블...,173,2:53,False,https://i.ytimg.com/vi_webp/ekr2nIex040/maxres...,ROSÉ,https://www.youtube.com/channel/UCBo1hnzxV9rz3...,19200000
1,"Lady Gaga, Bruno Mars - Die With A Smile (Offi...","Lady Gaga, Bruno Mars - Die With A Smile (Offi...",MAYHEM OUT NOW\nhttp://ladygaga.com \n \nListe...,1324833300,Music,Lady Gaga;Bruno Mars;Interscope;Pop,252,4:12,False,https://i.ytimg.com/vi/kPa7bsKwL-c/maxresdefau...,Lady Gaga,https://www.youtube.com/channel/UC07Kxew-cMIay...,29600000

In [22]:
# Multiple condition 
billion_viewed_music_LadyGaga = music_copy[(music_copy['view_count'] >= 1000000000) & (music_copy['channel'] == 'Lady Gaga')]
billion_viewed_music_LadyGaga

,title,fulltitle,description,view_count,categories,tags,duration,duration_string,live_status,thumbnail,channel,channel_url,channel_follower_count
1,"Lady Gaga, Bruno Mars - Die With A Smile (Offi...","Lady Gaga, Bruno Mars - Die With A Smile (Offi...",MAYHEM OUT NOW\nhttp://ladygaga.com \n \nListe...,1324833300,Music,Lady Gaga;Bruno Mars;Interscope;Pop,252,4:12,False,https://i.ytimg.com/vi/kPa7bsKwL-c/maxresdefau...,Lady Gaga,https://www.youtube.com/channel/UC07Kxew-cMIay...,29600000

In [23]:
# Using isin()
eilish_gaga_music = music_copy[music_copy['channel'].isin(['Billie Eilish', 'Sean Paul'])]
eilish_gaga_music

,title,fulltitle,description,view_count,categories,tags,duration,duration_string,live_status,thumbnail,channel,channel_url,channel_follower_count
3,Billie Eilish - BIRDS OF A FEATHER (Official M...,Billie Eilish - BIRDS OF A FEATHER (Official M...,Listen to HIT ME HARD AND SOFT: https://billie...,558329099,Music,Billie Eilish;Darkroom/Interscope Records;Alte...,231,3:51,False,https://i.ytimg.com/vi/V9PVRfjEBTI/maxresdefau...,Billie Eilish,https://www.youtube.com/channel/UCDGmojLIoWpXo...,56800000
9,Billie Eilish - WILDFLOWER (BILLIE BY FINNEAS),Billie Eilish - WILDFLOWER (BILLIE BY FINNEAS),HIT ME HARD AND SOFT (WITH ALL ISOLATED VOCALS...,40408980,Music,Billie Eilish;Darkroom/Interscope Records;Alte...,261,4:21,False,https://i.ytimg.com/vi/IWKyykQBRKo/maxresdefau...,Billie Eilish,https://www.youtube.com/channel/UCDGmojLIoWpXo...,56800000
27,Billie Eilish - CHIHIRO (Official Music Video),Billie Eilish - CHIHIRO (Official Music Video),"HIT ME HARD AND SOFT, the new album from Billi...",148501523,Music,Billie Eilish;Darkroom/Interscope Records;Alte...,324,5:24,False,https://i.ytimg.com/vi/BY_XwvKogC8/maxresdefau...,Billie Eilish,https://www.youtube.com/channel/UCDGmojLIoWpXo...,56800000
98,Sean Paul x INNA - Let It Talk To Me,Sean Paul x INNA - Let It Talk To Me,Song Title: Sean Paul x INNA - Let It Talk To ...,16952860,Music,Sean Paul,155,2:35,False,https://i.ytimg.com/vi_webp/nkRyAVQdqAA/maxres...,Sean Paul,https://www.youtube.com/channel/UCkdc7gHpavxpg...,5200000

In [24]:
# Using query()
query = music_copy.query('channel_follower_count > 1000000 and view_count > 1000000')
print("Number of music with more than 1 million views and more than 1 million followers: ", len(query))

Number of music with more than 1 million views and more than 1 million followers:  72

# Data Aggregation and Grouping

In [25]:
# Basic Aggregation Statistics
if 'duration' in music_copy.columns:
    print(f"Mean duration: {music_copy['duration'].mean():.2f}s")
    print(f"Median duration: {music_copy['duration'].median():.2f}s")
    print(f"Standard deviation of duration: {music_copy['duration'].std():.2f}s")

Mean duration: 203.90s
Median duration: 193.50s
Standard deviation of duration: 44.26s

In [26]:
# Value counts
if 'channel' in music_copy.columns:
    artist = music_copy['channel'].value_counts()
    print("Number of music tracks by artist:\n", artist)

Number of music tracks by artist:
 channel
Sabrina Carpenter    7
Tate McRae           4
The Weeknd           3
David Guetta         3
JENNIE               3
                    ..
Drake                1
GIVĒON               1
Charli xcx           1
Roy Woods            1
Post Malone          1
Name: count, Length: 65, dtype: int64

In [27]:
# Average duration of music by views count by applying categorization
if 'duration' in music_copy.columns and 'view_count' in music_copy.columns:
    # Create view count categories
    def categorize_views(views):
        if views < 100_000:
            return 'Under 100K'
        elif views < 500_000:
            return '100K - 500K'
        elif views < 1_000_000:
            return '500K - 1M'
        elif views < 1_000_000_000:
            return '1M - 1B'
        else:
            return 'Over 1B'
    # Apply categorization
    music_copy['view_category'] = music_copy['view_count'].apply(categorize_views)
    duration_by_views = music_copy.groupby('view_category')['duration'].mean()
    print("Average Duration by Views")
    print(duration_by_views)
    
    # Show count in each category
    print("\nNumber of songs in each category:")
    print(music_copy['view_category'].value_counts())

Average Duration by Views
view_category
100K - 500K    201.000000
1M - 1B        207.554217
500K - 1M      139.000000
Over 1B        212.500000
Under 100K     187.090909
Name: duration, dtype: float64

Number of songs in each category:
view_category
1M - 1B        83
Under 100K     11
Over 1B         2
100K - 500K     2
500K - 1M       2
Name: count, dtype: int64

# Pivot Table and Data Reshaping

In [28]:
# Pivot table
if 'duration' in music_copy.columns and 'channel' in music_copy.columns and 'view_category' in music_copy.columns:
    pivot_duration = pd.pivot_table(
        music_copy,
        values='duration',
        index='channel',
        columns='view_category',
        aggfunc='mean',
        fill_value=0
    )
    print("Average Duration by Channel and View Category:")
    print(pivot_duration.head())

Average Duration by Channel and View Category:
view_category  100K - 500K  1M - 1B  500K - 1M  Over 1B  Under 100K
channel
Addison Rae            0.0    180.0        0.0      0.0         0.0
Alex Warren            0.0    187.5        0.0      0.0         0.0
Ariana Grande          0.0    181.5        0.0      0.0         0.0
Benson Boone           0.0    175.0        0.0      0.0         0.0
Billie Eilish          0.0    272.0        0.0      0.0         0.0

In [29]:
# Data Reshaping: Melt Example
# Create a sample subset for melting
music_subset = music_copy[['title', 'channel', 'view_count', 'duration', 'channel_follower_count']].head(10)

# Melt the data to long format
melted_music = pd.melt(
    music_subset,
    id_vars=['title', 'channel'],
    value_vars=['view_count', 'duration', 'channel_follower_count'],
    var_name='metric',
    value_name='value'
)
print("Melted Data (Long Format):")
melted_music.sample(10)

Melted Data (Long Format):

,title,channel,metric,value
21,"Lady Gaga, Bruno Mars - Die With A Smile (Offi...",Lady Gaga,channel_follower_count,29600000
4,Reneé Rapp - Mad (Official Music Video),Reneé Rapp,view_count,2113548
16,Lady Gaga - Abracadabra (Official Music Video),Lady Gaga,duration,269
25,Sabrina Carpenter - Espresso,Sabrina Carpenter,channel_follower_count,12300000
28,yung kai - blue (official music video),yung kai,channel_follower_count,1220000
2,Reneé Rapp - Leave Me Alone (Official Music Vi...,Reneé Rapp,view_count,2536628
19,Billie Eilish - WILDFLOWER (BILLIE BY FINNEAS),Billie Eilish,duration,261
6,Lady Gaga - Abracadabra (Official Music Video),Lady Gaga,view_count,191073418
3,Billie Eilish - BIRDS OF A FEATHER (Official M...,Billie Eilish,view_count,558329099
17,Ed Sheeran - Sapphire (Official Music Video),Ed Sheeran,duration,183